version: '3'

services:
  chatx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - TONGYI_API_KEY=${TONGYI_API_KEY}
      - YUANBAO_API_KEY=${YUANBAO_API_KEY}